### PR TITLE
Impl queryBind

### LINKED ISSUE #98: Bug: queryBind causes premature termination in a exists method
### Describe the bug

In the exists method, the process terminates prematurely after the execution of queryBind. All subsequent code, including logging ("exist?: ...") and the return statement, is never executed. This issue only occurs when using .queryBind to execute the database query.

### Steps to reproduce

```java
public static boolean exists(String username, String email) {
    logger.info("step: 1");
    Response response = surreal().queryBind(
        "SELECT * FROM users WHERE username = $username AND email = $email;", 
        Map.of("username", username, "email", email)
    );
    logger.info("step: 2");

    boolean exist = response.take(User.class, 0) != null;
    logger.info("exist?: " + exist);

    return exist;
}
```

### Expected behaviour

The .queryBind method should not block or terminate the process. The subsequent code should execute correctly, logging whether the user exists and returning a boolean value.

### SurrealDB version

surreal 2.1.4

### Contact Details

m46955611@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by harry-xi**
Fixes #98

### CODE REVIEW

**Comment by harry-xi** [comment]
I found a little question: this implement doesn't support the value to be `null`. Is this important?

**Comment by massikhr** [comment]
I noticed that `Response.take(Class<T>, int)` throws a` NullPointerException` if the query returns no results instead of returning null or an empty instance. This makes error handling more difficult in cases where no matching entry exists.

Would it be possible to handle this case more gracefully by returning `null` or an empty object instead of throwing an exception?

Here is my stack trace when this issue occurs:

`java.lang.NullPointerException: Object instance not found
at com.surrealdb.Value.getObject(Native Method)
at com.surrealdb.Value.getObject(Value.java:109)
at com.surrealdb.ValueClassConverter.convert(ValueClassConverter.java:175)
at com.surrealdb.Value.get(Value.java:212)
at dev.massi.ayase.database.model.AyaseUser.lambda$findById$0(AyaseUser.java:74)`

**Comment by harry-xi** [comment]
> I noticed that `Response.take(Class<T>, int)` throws a `NullPointerException` if the query returns no results instead of returning null or an empty instance. This makes error handling more difficult in cases where no matching entry exists.
> 
> Would it be possible to handle this case more gracefully by returning `null` or an empty object instead of throwing an exception?

You should treat it as a separate issue as it is in fact relevant to the full range of scenarios involving Value to specific type conversions.

In fact I think in a scenario where None/Null might be returned in anticipation. A better way to handle this would be to get the original Value object directly from the Response then use its methods to determine if it is None/Null before converting it.

Further, the Value object provides comprehensive methods for determining whether the value in the Value is of a particular type, and they may be helpful.

**Comment by massikhr** [comment]
> > I noticed that `Response.take(Class<T>, int)` throws a `NullPointerException` if the query returns no results instead of returning null or an empty instance. This makes error handling more difficult in cases where no matching entry exists.
> > Would it be possible to handle this case more gracefully by returning `null` or an empty object instead of throwing an exception?
> 
> You should treat it as a separate issue as it is in fact relevant to the full range of scenarios involving Value to specific type conversions.
> 
> In fact I think in a scenario where None/Null might be returned in anticipation. A better way to handle this would be to get the original Value object directly from the Response then use its methods to determine if it is None/Null before converting it.
> 
> Further, the Value object provides comprehensive methods for determining whether the value in the Value is of a particular type, and they may be helpful.

Thanks for your response! That makes sense. So instead of directly calling `take(Class<T>, int)`, I should first check the `Value` object returned from the `Response` to determine if it is `None` or `Null` and only then proceed with conversion?

Could you provide an example of how to properly check if the Value is None or Null before calling `get(Class<T>)`? That would be really helpful!

Appreciate the clarification! 🚀

File: src/main/rust/surreal.rs [hunk 1]
```diff
@@ -207,6 +204,33 @@ pub extern "system" fn Java_com_surrealdb_Surreal_query<'local>(
...
+    params_keys: JObjectArray<'local>,
+    params_values: JLongArray<'local>,
+) -> jlong {
+    // Retrieve the Surreal instance
+    let surreal = get_surreal_instance!(&mut env, ptr, || 0);
+    // Retrieve the query
+    let query = get_rust_string!(&mut env,&query, || 0);
+    let keys = get_rust_string_array!(&mut env, params_keys, || 0);
+    let value_ptrs = get_long_array!(&mut env, &params_values, || 0);
+    let mut parems_map = BTreeMap::<String,&Value>::new();
```
Comment (emmanuel-keller) [inline src/main/rust/surreal.rs:222]:
```suggestion
    let mut params_map = BTreeMap::<String,&Value>::new();
```

File: src/main/rust/surreal.rs [hunk 2]
```diff
@@ -207,6 +204,33 @@ pub extern "system" fn Java_com_surrealdb_Surreal_query<'local>(
...
+    for (key,value_ptr) in keys.into_iter().zip(value_ptrs) {
+        let value = get_value_mut_instance!(&mut env, value_ptr, || 0);
+        parems_map.insert(key, value);
```
Comment (emmanuel-keller) [inline src/main/rust/surreal.rs:225]:
```suggestion
        params_map.insert(key, value);
```

File: src/main/rust/surreal.rs [hunk 3]
```diff
@@ -207,6 +204,33 @@ pub extern "system" fn Java_com_surrealdb_Surreal_query<'local>(
...
+    }
+    
+    let res = surrealdb_query::<&Value>(&surreal, &query, Some(parems_map));
```
Comment (emmanuel-keller) [inline src/main/rust/surreal.rs:228]:
```suggestion
    let res = surrealdb_query::<&Value>(&surreal, &query, Some(params_map));
```

**Review by emmanuel-keller — APPROVED** [review]
Great job! Just a typo!

**Comment by harry-xi** [comment]
I found #90 also be resolve by this pr.
